check if current path is in a git work tree

diff --git a/exec-on-git-staged b/exec-on-git-staged
--- a/exec-on-git-staged
+++ b/exec-on-git-staged
@@ -1,4 +1,11 @@
 #!/bin/bash
+
+# Fail if not in a git repo
+if ! `git rev-parse --is-inside-work-tree > /dev/null`
+then
+	exit 1
+fi
+
 # Remember path and setup temporary path
 REPO_DIRECTORY=`pwd`
 REPO_SLUG=`echo ${REPO_DIRECTORY} | sed --expression 's/\///'| sed --expression='s/\//-/g'`
